### PR TITLE
Feature: GraphQL Relay Node Interface

### PR DESCRIPTION
**Pull request by ericenns**
## What does this PR do and why?
_Describe in detail what your merge request does and why._

This PR updates the Group type to implement the Relay Node interface. This allows us to query Groups via Node or Nodes queries. This will be really useful later on when we add additional types as it will give our clients the ability to query different types of objects within a single query.

To achieve this I updated the Group type to implement the [Node interface](https://graphql-ruby.org/schema/object_identification.html#node-interface).

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

1. Login with 'user1@email.com` and then navigate to `http://localhost:3000/graphiql`
2. Query for a group that the user has access through the node interface
     ```graphql
     {
       node(id: "gid://irida/Group/18") {
         ... on Group {
           name
         }
       }
     }
     ```
3. See the result:
     ```json
     {
       "data": {
         "node": {
           "name": "Bartonella"
         }
       }
     }
     ```
4. Query for a group that the user does not have access to through the node interface
     ```graphql
     {
       node(id: "gid://irida/Group/18") {
         ... on Group {
           name
         }
       }
     }
     ```
5. See an error message
     ```json
     {
       "data": {
         "node": null
       },
       "errors": [
         {
           "message": "An object of type Group was hidden due to permissions",
           "locations": [
             {
               "line": 2,
               "column": 3
             }
           ],
           "path": [
             "node"
           ]
         }
       ]
     }
     ```
6. Look at the docs and try the nodes interface the same way, while searching for the same groups.

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] I have evaluated the PR acceptance checklist for this PR.

### CODE REVIEW

**Review by JeffreyThiessen — CHANGES_REQUESTED** [review]
Everything seems to be working, but I'm not sure I understand how the gid's get made/used. 
If I enter
```
{
  node(id: "gid://anytext/Group/2") {
    ... on Group {
      name
    }
  }
}
```
It still responds with with the data node as if `anytext` was `irida`. Is this intended?

**Comment by ericenns** [comment]
> Everything seems to be working, but I'm not sure I understand how the gid's get made/used. If I enter
> 
> ```
> {
>   node(id: "gid://anytext/Group/2") {
>     ... on Group {
>       name
>     }
>   }
> }
> ```
> 
> It still responds with with the data node as if `anytext` was `irida`. Is this intended?

[rails/globalid](https://github.com/rails/globalid) is used to generate the ids and find models based off of the ids. Since this PR didn't introduce the GlobalID functionality (it was added in the first GraphQL PR), I can create an issue to enforce that the `appname` of the passed GlobalID matches the configured `appname`.

**Review by JeffreyThiessen — APPROVED** [review]
Looks good. :+1:

**Review by deepsidhu85 — APPROVED** [review]
This looks great and working as expected. As to the comment above about being able to use any text in place of `irida` in the id still returns the results so yeah let's make an issue for it!

**Pull request merged**
