### PR TITLE
Attachments: Direct multiple upload

### PR DESCRIPTION
**Pull request by ericenns**
## What does this PR do and why?
_Describe in detail what your merge request does and why._

This PR changes the upload process to use direct upload (see https://blog.commutatus.com/understanding-rails-activestorage-direct-uploads-a4aeca7eccf). This also adds in a `Attachments::CreateService` which takes in a list of `files` so that multiple `Attachments` can be created in one go. Add in this service allows a user to upload multiple files at once instead of having to submit a single file per upload.

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

image

image

image

image

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

1. Login as your user of choice, and create a personal project
2. Create a Sample in the project you just created
3. Navigate to the Sample
4. Click `Upload Files`
5. Try clicking `Upload` in the modal with selecting any files
6. Try uploading a new file to the Sample
7. Try uploading files that already exist in the Sample

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

### CODE REVIEW

**Comment by deepsidhu85** [comment]
The code is looking good however I found some edge cases which aren't handled properly:

**1. If you upload files to a sample and then duplicate the tab, the duplicated tab doesn't show the uploaded files unless you reload the page**

**To test:**

1) Login as a user that has a project
2) From the samples page create a new sample
3) Upload a few files
4) Duplicate the tab. You should see no files listed
5) Now refresh the duplicated tab and you should see the files that were uploaded

**2. If you have multiple tabs open and you delete a file in one tab, switching to the other tab and attempting to delete that same file results in no feedback to the user. In this case I think we would want to remove the file object from the dom if the status is `not_found`**

**To test:**

1) Login as a user that has a project
2) From the samples page create a new sample
3) Upload some files
4) Open another tab and visit this project's samples page and view the sample that was created
5) In the first tab delete one of the files
6) Now in the second tab attempt to delete that same file
7) You should see no feedback and the file should still be listed
8) In the rails server console you should see `Completed 404 Not Found`

**Review by deepsidhu85 — CHANGES_REQUESTED** [review]
This looks good just found some edge cases which I left in a general comment on the PR. One other thing I was thinking is we should probably list the files selected to be uploaded in the Upload modal since the input box just displays `n files` where n is a number

**Comment by ericenns** [comment]
> * Login as a user that has a project
> * From the samples page create a new sample
> * Upload a few files
> * Duplicate the tab. You should see no files listed
> * Now refresh the duplicated tab and you should see the files that were uploaded

I am unable to reproduce the first edge case. What I did is as follows:
1. Create a Personal Project and a Sample in that project
2. Upload a file to that sample
3. Open the sample page in another tab

When I open the page I see the files. Maybe you opened the other tab while the upload was still being performed so that could only be the reason that it was empty?

For the second edge case, this PR does not introduce deleting, i.e. that bug was already present. I think that should instead be created into its own issue to be addressed separately from this PR.

**Comment by deepsidhu85** [comment]
> > * Login as a user that has a project
> > * From the samples page create a new sample
> > * Upload a few files
> > * Duplicate the tab. You should see no files listed
> > * Now refresh the duplicated tab and you should see the files that were uploaded
> 
> I am unable to reproduce the first edge case. What I did is as follows:
> 
> 1. Create a Personal Project and a Sample in that project
> 2. Upload a file to that sample
> 3. Open the sample page in another tab
> 
> When I open the page I see the files. Maybe you opened the other tab while the upload was still being performed so that could only be the reason that it was empty?
> 
> For the second edge case, this PR does not introduce deleting, i.e. that bug was already present. I think that should instead be created into its own issue to be addressed separately from this PR.

Yeah sorry I should've prefaced the second edge case with it should be addressed in a separate PR. As discussed the first edge case is likely using the browser cache to display the page

**Review by deepsidhu85 — APPROVED** [review]

**Pull request merged**
