### PR TITLE
Submit search on enter

### PR DESCRIPTION
**Pull request by joshsadam**
## What does this PR do and why?
_Describe in detail what your merge request does and why._

1. Standardized Search Component
2. Search now works when the `enter` key is pressed, not debounced

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

image

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

Ensure that search still works across the project (tested through our integration tests as well)

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [X] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

### CODE REVIEW

**Review by ChrisHuynh333 — DISMISSED** [review]
Just through usage on the website, I noticed a few inconsistencies. This is assuming we want the search field to still be populated with the search after hitting enter, and to have focus on the search bar. As well as after leaving the page, the filter would be removed

- Projects dashboard - Search field is emptied and not focused after search
- Groups dashboard - If I leave the groups dashboard page and come back, the search bar is still populated with the search but the groups are not filtered
- Data Exports - Search field is emptied and not focused after search
- Samples - Search and filter are still enabled after leaving and coming back to the page
- Project Files - Search field is emptied and not focused after search

I also think if the user clicks on the "X" at the end of the search bar, that should return an unfiltered request, thoughts?

**Comment by ericenns** [comment]
> Just through usage on the website, I noticed a few inconsistencies. This is assuming we want the search field to still be populated with the search after hitting enter, and to have focus on the search bar. As well as after leaving the page, the filter would be removed
> 
> * Projects dashboard - Search field is emptied and not focused after search
> * Groups dashboard - If I leave the groups dashboard page and come back, the search bar is still populated with the search but the groups are not filtered
> * Data Exports - Search field is emptied and not focused after search
> * Samples - Search and filter are still enabled after leaving and coming back to the page
> * Project Files - Search field is emptied and not focused after search
> 
> I also think if the user clicks on the "X" at the end of the search bar, that should return an unfiltered request, thoughts?

Samples table search is expected to be different as we store that server side, but I agree with your remaining comments.

**Comment by joshsadam** [comment]
@ChrisHuynh333 & @ericenns Those pages are updated along with tests

**Review by ericenns — APPROVED** [review]
Looks good to me!

**Pull request merged**
