### PR TITLE
Groups dashboard searching sorting

### PR DESCRIPTION
**Pull request by joshsadam**
## What does this PR do and why?
_Describe in detail what your merge request does and why._

Added search by group name or puid through text input field above tree component.  When search is active, the tree becomes "flat".

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

image

image

image

**Empty search result**
image

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

1. Go to groups dashboard page
2. Expand `Streptococcus` row and should have child groups
3. Filter by `strep` and should see a flatten listing of all stretococcus groups
4. Try also filter by PUID

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [X] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

### CODE REVIEW

**Review by deepsidhu85 — CHANGES_REQUESTED** [review]
Just a quick comment to start. When searching and no results are returned, can be display some text to notify the user that no groups were found?

**Review by deepsidhu85 — CHANGES_REQUESTED** [review]
Can you please update the variable `flat` below and anywhere it is used for clarity

**Review by deepsidhu85 — APPROVED** [review]
Looks good to me!

**Review by ericenns — APPROVED** [review]
Looks good to me!

**Pull request merged**
