### PR TITLE
WES: Update run workflow to use multipart form data

### PR DESCRIPTION
**Pull request by ericenns**
## What does this PR do and why?
_Describe in detail what your merge request does and why._

This updates the GA4GH WES Api connector to use `multipart-form-data` when submitting a request to the `run_workflow` endpoint which is alignment with the WES 1.1.0 spec.

Additionally the PR does the following:
- Updates `as_wes_params` to format the params correctly for use as form data
- Removes `--` and `-` prefixes from `workflow_params` as we are now specifying them as a `json` in nextflow command line (e.g. `nextflow -params-file params.json`)
- Specify workflow version via `worfklow_engine_parameters` (e.g. `{"-r": "dev"}`)

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

1. Setup my fork of `sapporo-service` (a WES implementation)
```bash
git clone git@github.com:phac-nml/sapporo-service.git
cd sapporor-service
git checkout irida-next
IRIDA_NEXT_PATH=/PATH/TO/IRIDA/NEXT/REPO docker compose -f compose.irida-next.yml up -d --build
IRIDA_NEXT_PATH=/PATH/TO/IRIDA/NEXT/REPO docker compose -f compose.irida-next.yml exec app bash
sapporo
```
2. Configure IRIDA Next to use `sapporo-service`
```bash
EDITOR=vim bin/rails credentials:edit
```
Add
```
ga4gh_wes:
  server_url_endpoint: http://localhost:1122/
```
3. Start rails server
4. Submit a pipeline and see it go through all the stages to complete (note: may need to add `1.0.3` version to `config/pipelines/pipelines.json` and when submitting pipeline clear out `--random_seed` param)

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

### CODE REVIEW

**Review by JeffreyThiessen — DISMISSED** [review]
Tested with a handful of runs on sapporo, looks good. :+1:

**Comment by JeffreyThiessen** [comment]
One tiny change actually, Please update `scripts/clean_dev.sh` to cleanup storage with force `rm -rf storage/*` as files generated by sapporo are write protected.

**Comment by ericenns** [comment]
> One tiny change actually, Please update `scripts/clean_dev.sh` to cleanup storage with force `rm -rf storage/*` as files generated by sapporo are write protected.

Fixed in 8805233

**Review by deepsidhu85 — DISMISSED** [review]
Looks good to me! Thanks for getting this working so we can test submissions!

**Review by JeffreyThiessen — APPROVED** [review]
Looks good :+1:

**Review by deepsidhu85 — APPROVED** [review]
Looks good to me!

**Pull request merged**
