### PR TITLE
enhancement: Updated navigation layout

### PR DESCRIPTION
**Pull request by joshsadam**
## What does this PR do and why?
_Describe in detail what your merge request does and why._

After reading a recent blog post from GitLab,[ Inside the vision for GitLab's new platform navigation](https://about.gitlab.com/blog/2023/05/01/gitlab-product-navigation/),  we have decided to update the navigation of this version of IRIDA to reflect their research.

Please note:

1. There are still some updates to the cards (going to give them an off-white background), but that will be done in a separate PR which will fix cards that are not from the component.
2. Dark mode button is going to be moved into the user profile section.  This will also be done in a subsequent PR.  If you want to test out dark mode, you can change it manually in the storage tab of the browser developer tools.

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

image

image

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] I have evaluated
  the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

### CODE REVIEW

**Review by ericenns — CHANGES_REQUESTED** [review]
Can you fix the inconsistencies between the light mode and dark mode. See below:

image

image

**Review by ksierks — COMMENTED** [review]
I had no idea we had collapsed/expanded layout capabilities. Maybe it's the new icon. Nice!

I know you mentioned you were going to continue working on dark/light mode in another PR, but I noticed these new errors:

image
image

**Comment by joshsadam** [comment]
> Can you fix the inconsistencies between the light mode and dark mode. See below:

Thanks @ericenns updated in ed24723

**Comment by ericenns** [comment]
I found another issue, the styling on the personal access tokens page changes when revoking a token.

Before:
MicrosoftTeams-image (7)


After:
image

**Comment by joshsadam** [comment]
> Bad merge in Project Settings, see below: 

Thanks, fixed in 83ae05e

**Review by ericenns — APPROVED** [review]
Looks good to me!

Dark/Light mode will need to addressed in a follow up pr.

**Pull request merged**
