### PR TITLE
Fix create project form errors

### LINKED ISSUE #171: Project Creation Form Errors not displaying
## Problem

Errors are not displaying on the Project creation form when validation fails. Instead the form just redisplays and does not indicate to the user that a problem prevented the Project from being created.

## Steps to reproduce
1. From the Projects Dashboard click `New project`
2. Fill in `Project Name` and `Path` with `a`
3. Click `Create project`
4. See that the form is re-rendered and no fields are show as in error and no errors are displayed.
5. Navigate back to Projects Dashboard and confirm that no project is created as expected.

## Solution
Update Project Form to display errors when Project is not created due to failing validation, refer to Group Form on how we detect and display errors.

### PR DESCRIPTION
**Pull request by ksierks**
## What does this PR do and why?
Updated Project Form to display errors when Project is not created due to failing validation, refer to Group Form on how we detect and display errors.
Fixes #171.

## Screenshots or screen recordings
Screenshot from 2023-09-15 09-52-32
Screenshot from 2023-09-15 09-55-08
Screenshot from 2023-09-15 12-42-30

## How to set up and validate locally
1. From the Projects Dashboard click `New project`
2. Fill in `Project Name` and `Path` with `a`
3. Click `Create project`
4. See that the form is re-rendered and fields show errors are displayed.
5. Navigate back to Projects Dashboard and confirm that no project is created as expected.

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

### CODE REVIEW

**Review by deepsidhu85 — APPROVED** [review]
This looks good to me! Great work!

**Review by JeffreyThiessen — CHANGES_REQUESTED** [review]
I found some issues with the UI
1. On firefox the formatting does not show the correct styling, just having a plain textbox with no warning icon.
image

2. On firefox, the info box is always dark mode styling (still incorrect as per 1)
image

3. The info box for the error does not have dark mode styling (chrome).
image

**Comment by deepsidhu85** [comment]
> I found some issues with the UI
> 
> 1. On firefox the formatting does not show the correct styling, just having a plain textbox with no warning icon.
>    image
> 2. On firefox, the info box is always dark mode styling (still incorrect as per 1)
>    image
> 3. The info box for the error does not have dark mode styling (chrome).
>    image

@JeffreyThiessen I'm not sure if we will be able to modify the styling for the browser validation messages but maybe there is a way that @joshsadam  or @ericenns can think of. Also, as this is probably the case for all our forms that use this kind of validation, this fix if possible, should be done in a separate PR

**Comment by JeffreyThiessen** [comment]
> @JeffreyThiessen I'm not sure if we will be able to modify the styling for the browser validation messages but maybe there is a way that @joshsadam or @ericenns can think of. Also, as this is probably the case for all our forms that use this kind of validation, this fix if possible, should be done in a separate PR

Oh if it's just differences in browser messages and not a styling thing on our end then it good. I thought these differences were on our codes side.

**Review by JeffreyThiessen — APPROVED** [review]
:+1:

**Pull request merged**
