### PR TITLE
Attachments: Checksum Uniqueness Validation

### PR DESCRIPTION
**Pull request by ericenns**
## What does this PR do and why?
_Describe in detail what your merge request does and why._

This PR introduces Checksum uniqueness validation to the `Attachment` model. This prevents more than one `Attachment` from being associated to an `Attachable` where the `file` computed checksum matches an existing `file` in another `Attachment` associated with the `Attachable`.

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

image

image

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

1. Upload `test_file.fastq` to a Sample. 
2. Attempt to reupload `test_file.fastq` to the same Sample.
3. See that an error message appears and that the file was not uploaded.

Note: `test_file.fastq` can be found at `test/fixtures/files` in the repository.

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

### CODE REVIEW

**Review by ksierks — APPROVED** [review]
That was fun. I tried deleting the last character in the same file. Works as expected.

**Review by JeffreyThiessen — CHANGES_REQUESTED** [review]
Looks good :+1: 

The code is clean and easy to understand. 
I went through a couple edge cases (sym links, hard links, files within files, etc) to try to trick the checksum but it handled them all.

I found 1 strange issue, I'm not sure if it's a issue with the checksum popup or the samples page.

Issue: The list of files changes height as the checksum popup is interacted with.
Steps to reproduce.
1. Click [Upload File] 
2. in the `Upload New File` popup, click [Upload File] repeatedly to see the file list move
3. clicking the [x] to close also shifts the file list an additional time
image
image

image

image

**Comment by deepsidhu85** [comment]
> Looks good 👍
> 
> The code is clean and easy to understand. I went through a couple edge cases (sym links, hard links, files within files, etc) to try to trick the checksum but it handled them all.
> 
> I found 1 strange issue, I'm not sure if it's a issue with the checksum popup or the samples page.
> 
> Issue: The list of files changes height as the checksum popup is interacted with. Steps to reproduce.
> 
> 1. Click [Upload File]
> 2. in the `Upload New File` popup, click [Upload File] repeatedly to see the file list move
> 3. clicking the [x] to close also shifts the file list an additional time
>    image
>    image
> 
> image
> 
> image

@JeffreyThiessen @ericenns I tried out the PR in both light and dark mode and was not able to reproduce the issue. @JeffreyThiessen  what browser were you using?

**Review by JeffreyThiessen — APPROVED** [review]
Looks good. :+1:

**Pull request merged**
