### PR TITLE
Attachments: File presence validation

### PR DESCRIPTION
**Pull request by ericenns**
## What does this PR do and why?
_Describe in detail what your merge request does and why._

Adds in active-storage-validations gem, and updates Attachment model to validate that the `file` is attached (i.e. ensure that file is associated with the attachment).

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

image

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

1. Navigate to a Sample and attempt to upload file without selecting a file.
2. Ensure that a error shows up in the form indicating that file can't be blank.

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

### CODE REVIEW

**Review by joshsadam — APPROVED** [review]
Thanks for fixing this.

**Review by deepsidhu85 — CHANGES_REQUESTED** [review]
This looks good and working as expected. One thing I noticed is the placement of the error message is kind of off. It should be more aligned with the starting of the input

image

**Comment by joshsadam** [comment]
> This looks good and working as expected. One thing I noticed is the placement of the error message is kind of off. It should be more aligned with the starting of the input

@deepsidhu85 I am fixing this in a subsequent PR

**Comment by deepsidhu85** [comment]
> > This looks good and working as expected. One thing I noticed is the placement of the error message is kind of off. It should be more aligned with the starting of the input
> 
> @deepsidhu85 I am fixing this in a subsequent PR

Awesome thanks! Good to go then!

**Pull request merged**
