### PR TITLE
Member destroy turbostream

### PR DESCRIPTION
**Pull request by deepsidhu85**
## What does this PR do and why?
_Describe in detail what your merge request does and why._

This PR updates group/project members destroy to work via turbo_stream.

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

1. Login as any user
2. Add a member as a direct member to a subgroup where the user is also a member of an ancestor
3. Now remove this user from the subgroup
4. Verify that the member's ancestor inheritance is displayed
5. Verify in the network tab of the browser dev tools that the request/ was sent via turbo_stream
6. Verify page is not reloaded but rather the user's inherited membership is appended to the table

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] I have evaluated
  the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

### CODE REVIEW

**Review by ericenns — CHANGES_REQUESTED** [review]
This does quite work as expected. I.e. removing just the row can lead to a situation where the table is funky. Instead the whole page should be reloaded.

Steps to reproduce:
1. uncomment line 15 in `config/intiializers/pagy.rb` and set the value to `5`
2. Navigate to a group and add members till there are 6.
3. Navigate to the last page and then remove the member.
4. observe behaviour below

image

**Comment by deepsidhu85** [comment]
> This does quite work as expected. I.e. removing just the row can lead to a situation where the table is funky. Instead the whole page should be reloaded.
> 
> Steps to reproduce:
> 
> 1. uncomment line 15 in `config/intiializers/pagy.rb` and set the value to `5`
> 2. Navigate to a group and add members till there are 6.
> 3. Navigate to the last page and then remove the member.
> 4. observe behaviour below
> 
> image

Good catch. Updated in de7ed4cc91a2cac0a77ad51800dbfb072812f2b0 so the members table is reloaded instead of just having single rows removed from the dom

**Review by ericenns — APPROVED** [review]
This looks good to me!

**Review by joshsadam — APPROVED** [review]
Works as advertised and looks good. Can be merged once your tests pass.

**Pull request merged**
