### PR TITLE
Project member under user namespace removal

### PR DESCRIPTION
**Pull request by deepsidhu85**
## What does this PR do and why?
_Describe in detail what your merge request does and why._

Fixed bug preventing removal of user from a project under a user namespace. 

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

1. Login as any user
2. Create a project under the user's namespace
3. Add a few members to the project
4. Try removing a user. Verify that the user has been removed

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [X] I have evaluated
  the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

### CODE REVIEW

**Review by ericenns — CHANGES_REQUESTED** [review]
I found a bug where an owner of a Project that belongs to another UserNamespace cannot leave the project.

e.g.
1. As `user1@email.com` create a project called `test`
2. Add `admin@email.com` as a Owner to project `test`
3. Logout and login as `admin@email.com`
4. Attempt to leave the project.
image

**Comment by deepsidhu85** [comment]
> I found a bug where an owner of a Project that belongs to another UserNamespace cannot leave the project.
> 
> e.g.
> 
> 1. As `user1@email.com` create a project called `test`
> 2. Add `admin@email.com` as a Owner to project `test`
> 3. Logout and login as `admin@email.com`
> 4. Attempt to leave the project.
>    image

Fixed in 83c0fda1eaba47d1f6b4de9aa341263c0cfe4bac. As discussed just fixing it for now but the long term fix is to remove the owner column from the namespace and create an actual member withing the project for the user who owns the project (is under their namespace)

**Comment by ericenns** [comment]
> fixing it for now but the long term fix is to remove the owner column from the namespace and create an actual member withing the project for the user who owns the project (is under their namespace)

So actually what I was suggesting is that the owner of a `UserNamespace` actually has a corresponding `Member` entry with role `owner` I am happy how the project is currently, though `ProjectNamespace` does not need a `owner` attribute either.

**Review by ericenns — APPROVED** [review]
Looks good to me!

**Pull request merged**
