### PR TITLE
Local time

### PR DESCRIPTION
**Pull request by ChrisHuynh333**
## What does this PR do and why?
This PR adjusts `datetimes` on the website to use the user's local time. This includes removing our previous `viral_time_ago` component and using `local_time` gem's `time_ago`

Datepicker will be updated in a future PR

## Screenshots or screen recordings
image

image

## How to set up and validate locally
1. Navigate throughout the website wherever there is a timestamp, and verify the time is adjusted to your timezone.
This includes:
- Project/Group listing table
- Members table
- Samples table
- History
- Workflow Executions table
- Data Exports table
- Bots table
- PAT table

2. Navigate to Data Exports Mailer preview (http://localhost:3000/rails/mailers/data_export_mailer/). Ensure the datetime shown for expiry includes `23:59 UTC`

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

### CODE REVIEW

**Review by ericenns — CHANGES_REQUESTED** [review]
I did a search for `_at` in `app/views,app/components` and there are still quite a few instances of displaying time that don't use the users local time zone. This includes `UpdatedComponent`. Could you please perform this same search and ensure the other instances are properly displayed in the users time zone.

**Review by joshsadam — COMMENTED** [review]
This looks good.  I will take another look after the changes that @ericenns requested.  I have no other change requests at this time, good work.

**Review by joshsadam — APPROVED** [review]
This looks fantastic to me!

**Review by ericenns — APPROVED** [review]
Looks good to me!

**Pull request merged**
