### PR TITLE
Disable automated pipelines

### LINKED ISSUE #819: Disabled automated pipelines
## Summary

Currently within IRIDA Next, a previously automated and executable pipeline can be updated to not be executable or automated through the config. If one of these pipelines are set-up for a project, there is no way for the users to be notified that the pipeline is no longer executable, automated, or both

## Acceptance Criteria
- Database column to store if the pipeline is enabled/disabled
- `config/initializers/pipelines.rb` initializer updated to contain an after_`initialize hook` which will update the automated workflow executions table to set the enabled/disabled state of the automated pipeline. See the link below for more information on initializers 
- UI: Automated workflow executions table within projects updated to include this new state column

## Links

https://guides.rubyonrails.org/configuring.html#initialization-events

### PR DESCRIPTION
**Pull request by ksierks**
## What does this PR do and why?
Added a new status column to the automated pipelines table to show if the pipeline is enabled/disabled. 
Fixes #819.

## Screenshots or screen recordings
image

## How to set up and validate locally
1. Create an automated workflow execution within a project.
2. Remember the workflow name and version.
3. Modify the pipeline within the config/pipelines/pipelines.json file with `"automatable": false` or `"executable": false` or both or remove it entirely.
4. Restart irida-next.
5. Navigate to the project automation workflow executions page.
6. Verify the newly added automated workflow execution is disabled.

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

### CODE REVIEW

**Review by ChrisHuynh333 — APPROVED** [review]
Looks good and works as described!

**Review by ericenns — CHANGES_REQUESTED** [review]
This is working as expected, but I did find an edge case that was not previously documented where a pipeline entry removed from the config file would still leave an automated pipeline as enabled if it was enabled prior to removing from the config file.

**Review by deepsidhu85 — CHANGES_REQUESTED** [review]
This looks good to me just have one small comment

**Review by ericenns — APPROVED** [review]
Looks good to me

**Pull request merged**
