### PR TITLE
GraphQL - Project Attachment Resolver + AttachFilesToProject Mutation

### PR DESCRIPTION
**Pull request by JeffreyThiessen**
## What does this PR do and why?
_Describe in detail what your merge request does and why._
Adds `attachments` as a field to GraphQL `projects` query

adds `attach_files_to_project` GraphQL mutation

refactored duplicate functions from `AttachFilesToSample` into `BaseMutation`

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

### Test getting, filtering and ordering of attachments
1. Sign in with user1
2. go to GraphiQL
3. test filtering and ordering
```graphql
query get_project_attachments{
  projects(first:1){
    nodes{
      name
      attachments(
        filter:{filename_end:".fastq.gz"}
        orderBy:{field:created_at, direction:asc}
      ){
        totalCount
        nodes{
          filename
          createdAt
        }
      }
    }
  }
}
```
### Test attaching files to project
5. First wipe the db and seed without files
```bash
bin/rails info db:drop db:create db:migrate
SEED_MAXIMUM_TOTAL_SAMPLE_ATTACHMENTS=0 bin/rails info db:seed
```
6. sign into admin and go to GraphiQL
7. Get a project you have ownership of
```graphql
query get_proj{
  projects(first:1){
    nodes{
      name
      fullName
      puid
    }
  }
}
```

We will use the `puid`

8. Create a blob for your file
File: https://github.com/phac-nml/irida-next/files/14129150/myfile.json
```graphql
mutation makeblob {
  createDirectUpload(
    input: {
      filename: "myfile.json", # file name
      contentType: "application/json", # file content type
      checksum: "Y33CgI35hFoI6p+WBXYl+A==", # md5
      byteSize: 151 # size in bytes
    }
  ) {
    directUpload {
      url,
      headers,
      blobId,
      signedBlobId
    }
  }
}
```

We will use `url`, `headers` and `signedBlobId`

9. Upload your file

Using Postman, make a `PUT` request, using the returned `url` from above
image

Attach the file as a binary
image

Verify your content type matches the `headers` from above. Postman should auto-generate this based on the file you attached.

When `Send` is clicked, you should receive a `204 No Content`

10. Use the new mutation to attach the file to the project
```graphql
mutation attachfilestoproject {
  attachFilesToProject (
    input: {
      files: ["YOUR signedBlobId FROM ABOVE"],
      projectPuid: "YOUR puid FROM ABOVE"
    }
  ) {
    errors{
       path
       message
    },
    project{
      name
      puid
    }
    status
  }
}
```

11. Expected response
```json
{
  "data": {
    "attachFilesToProject": {
      "errors": [],
      "project": {
        "name": "Outbreak 2022",
        "puid": "YOUR puid FROM ABOVE"
      },
      "status": {
        "YOUR signedBlobId FROM ABOVE": "success"
      }
    }
  }
}
```

12. Check that the file was attached
```graphql
query get_project_attachments{
  projects(first:1){
    nodes{
      fullName
      name
      puid
      attachments{
        totalCount
        nodes{
          filename
          byteSize
          createdAt
        }
      }
    }
  }
}
```

13. Expected response

```graphql
{
  "data": {
    "projects": {
      "nodes": [
        {
          "fullName": "Bacillus / Bacillus anthracis / Outbreak 2022",
          "name": "Outbreak 2022",
          "puid": "YOUR puid FROM ABOVE",
          "attachments": {
            "totalCount": 1,
            "nodes": [
              {
                "filename": "myfile.json",
                "byteSize": 151,
                "createdAt": "2024-09-12T20:56:48Z"
              }
            ]
          }
        }
      ]
    }
  }
}
```

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

### CODE REVIEW

**Comment by JeffreyThiessen** [comment]
This PR is working as intended, but there is some kind of problem with bot accounts not having permission to attach files to projects even when they have permission and a valid token. The test case that is failing is from this issue, I'm not sure if it's the result of this PR or one of the other namespace/project changes made this week.

**Comment by ericenns** [comment]
> This PR is working as intended, but there is some kind of problem with bot accounts not having permission to attach files to projects even when they have permission and a valid token. The test case that is failing is from this issue, I'm not sure if it's the result of this PR or one of the other namespace/project changes made this week.

The test case is failing because `can_view_attachments?` and `can_create_attachments?` only allow `Maintainer` and `Owners` to perform the action. To make this work with `Uploader` you could refactor those two methods to be more like `can_modify_sample?`, the methods can be found in `app/models/member.rb`.

**Comment by ChrisHuynh333** [comment]
> This PR is working as intended, but there is some kind of problem with bot accounts not having permission to attach files to projects even when they have permission and a valid token. The test case that is failing is from this issue, I'm not sure if it's the result of this PR or one of the other namespace/project changes made this week.

Hey Jeff, sorry for overlooking this. The fix has been merged to main and will fix the testing issues you were having

**Review by ChrisHuynh333 — APPROVED** [review]
Looks good!

**Review by ericenns — APPROVED** [review]
Looks good to me!

**Pull request merged**
